### ISSUE TITLE
How to change root folder in jar for scanning?

### ISSUE THREAD

**Issue by alexsuter** [classgraph/classgraph#245]
I have to scan some jars, where all the classes are in the folder `classes` within the jar file. If I use now 

```java
ClassInfoList classInfolist = new ClassGraph()
            .verbose()
            .enableAllInfo()
            .overrideClasspath("/tmp/custom.jar!/classes")
            .scan()
            .getAllClasses();
```

They seems to get ignored?
Do I have to implement a custom classloader? 

Verbose Log:

```
2018-08-30T14:21:54.103+0200	ClassGraph	ClassGraph version 4.1.3
2018-08-30T14:21:54.108+0200	ClassGraph	Operating system: Linux 4.15.0-33-generic amd64
2018-08-30T14:21:54.108+0200	ClassGraph	Java version: 1.8.0_181 / 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13 (Oracle Corporation)
2018-08-30T14:21:54.108+0200	ClassGraph	JRE jars:
2018-08-30T14:21:54.108+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar
2018-08-30T14:21:54.108+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar
2018-08-30T14:21:54.108+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/cldrdata.jar
2018-08-30T14:21:54.108+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/dnsns.jar
2018-08-30T14:21:54.108+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/icedtea-sound.jar
2018-08-30T14:21:54.108+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/jaccess.jar
2018-08-30T14:21:54.108+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/java-atk-wrapper.jar
2018-08-30T14:21:54.108+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/jfxrt.jar
2018-08-30T14:21:54.108+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/localedata.jar
2018-08-30T14:21:54.108+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/nashorn.jar
2018-08-30T14:21:54.108+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunec.jar
2018-08-30T14:21:54.108+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunjce_provider.jar
2018-08-30T14:21:54.108+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunpkcs11.jar
2018-08-30T14:21:54.108+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/zipfs.jar
2018-08-30T14:21:54.108+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar
2018-08-30T14:21:54.108+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfxswt.jar
2018-08-30T14:21:54.108+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar
2018-08-30T14:21:54.108+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/management-agent.jar
2018-08-30T14:21:54.108+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar
2018-08-30T14:21:54.108+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/lib/ant-javafx.jar
2018-08-30T14:21:54.108+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/lib/dt.jar
2018-08-30T14:21:54.109+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/lib/javafx-mx.jar
2018-08-30T14:21:54.109+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/lib/jconsole.jar
2018-08-30T14:21:54.109+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/lib/sa-jdi.jar
2018-08-30T14:21:54.109+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/lib/tools.jar
2018-08-30T14:21:54.112+0200	ClassGraph	ScanSpec:
2018-08-30T14:21:54.112+0200	ClassGraph	-- packageWhiteBlackList: 
2018-08-30T14:21:54.112+0200	ClassGraph	-- packagePrefixWhiteBlackList: 
2018-08-30T14:21:54.112+0200	ClassGraph	-- pathWhiteBlackList: 
2018-08-30T14:21:54.112+0200	ClassGraph	-- pathPrefixWhiteBlackList: 
2018-08-30T14:21:54.113+0200	ClassGraph	-- classWhiteBlackList: 
2018-08-30T14:21:54.113+0200	ClassGraph	-- classfilePathWhiteBlackList: 
2018-08-30T14:21:54.113+0200	ClassGraph	-- classPackageWhiteBlackList: 
2018-08-30T14:21:54.113+0200	ClassGraph	-- classPackagePathWhiteBlackList: 
2018-08-30T14:21:54.113+0200	ClassGraph	-- moduleWhiteBlackList: 
2018-08-30T14:21:54.113+0200	ClassGraph	-- jarWhiteBlackList: 
2018-08-30T14:21:54.113+0200	ClassGraph	-- libOrExtJarWhiteBlackList: 
2018-08-30T14:21:54.113+0200	ClassGraph	-- performScan: true
2018-08-30T14:21:54.113+0200	ClassGraph	-- scanJars: true
2018-08-30T14:21:54.113+0200	ClassGraph	-- scanNestedJars: true
2018-08-30T14:21:54.113+0200	ClassGraph	-- scanDirs: true
2018-08-30T14:21:54.113+0200	ClassGraph	-- scanModules: true
2018-08-30T14:21:54.113+0200	ClassGraph	-- enableClassInfo: true
2018-08-30T14:21:54.113+0200	ClassGraph	-- enableFieldInfo: true
2018-08-30T14:21:54.113+0200	ClassGraph	-- enableMethodInfo: true
2018-08-30T14:21:54.113+0200	ClassGraph	-- enableAnnotationInfo: true
2018-08-30T14:21:54.113+0200	ClassGraph	-- enableStaticFinalFieldConstantInitializerValues: true
2018-08-30T14:21:54.113+0200	ClassGraph	-- enableExternalClasses: false
2018-08-30T14:21:54.113+0200	ClassGraph	-- blacklistSystemJarsOrModules: true
2018-08-30T14:21:54.114+0200	ClassGraph	-- ignoreClassVisibility: true
2018-08-30T14:21:54.114+0200	ClassGraph	-- ignoreFieldVisibility: true
2018-08-30T14:21:54.114+0200	ClassGraph	-- ignoreMethodVisibility: true
2018-08-30T14:21:54.114+0200	ClassGraph	-- disableRuntimeInvisibleAnnotations: false
2018-08-30T14:21:54.114+0200	ClassGraph	-- addedClassLoaders: null
2018-08-30T14:21:54.114+0200	ClassGraph	-- overrideClassLoaders: null
2018-08-30T14:21:54.114+0200	ClassGraph	-- overrideClasspath: /home/als/Downloads/ProjectWithAnnotations.iar!/classes
2018-08-30T14:21:54.114+0200	ClassGraph	-- classpathElementFilters: null
2018-08-30T14:21:54.114+0200	ClassGraph	-- extraClassLoaderHandlers: []
2018-08-30T14:21:54.114+0200	ClassGraph	-- initializeLoadedClasses: false
2018-08-30T14:21:54.114+0200	ClassGraph	-- removeTemporaryFilesAfterScan: false
2018-08-30T14:21:54.114+0200	ClassGraph	-- ignoreParentClassLoaders: false
2018-08-30T14:21:54.114+0200	ClassGraph	-- stripSFXHeader: false
2018-08-30T14:21:54.115+0200	ClassGraph	Finding classpath entries
2018-08-30T14:21:54.119+0200	ClassGraph	-- Getting raw classpath elements
2018-08-30T14:21:54.120+0200	ClassGraph	---- Finding ClassLoaders and modules
2018-08-30T14:21:54.124+0200	ClassGraph	------ Found ClassLoaders:
2018-08-30T14:21:54.124+0200	ClassGraph	-------- sun.misc.Launcher$AppClassLoader@6c629d6e
2018-08-30T14:21:54.124+0200	ClassGraph	-------- java.net.URLClassLoader@1c6a515d
2018-08-30T14:21:54.124+0200	ClassGraph	------ Adding fallback URLClassLoader for overriden classpath: java.net.URLClassLoader@1c6a515d
2018-08-30T14:21:54.124+0200	ClassGraph	------ Found system modules:
2018-08-30T14:21:54.124+0200	ClassGraph	-------- [None]
2018-08-30T14:21:54.124+0200	ClassGraph	------ Found non-system modules:
2018-08-30T14:21:54.124+0200	ClassGraph	-------- [None]
2018-08-30T14:21:54.125+0200	ClassGraph	------ Overriding classpath with: /home/als/Downloads/ProjectWithAnnotations.iar!/classes
2018-08-30T14:21:54.125+0200	ClassGraph	-------- Found classpath element: /home/als/Downloads/ProjectWithAnnotations.iar!/classes
2018-08-30T14:21:54.126+0200	ClassGraph	------ WARNING: when the classpath is overridden, there is no guarantee that the classes found by classpath scanning will be the same as the classes loaded by the context classloader
2018-08-30T14:21:54.126+0200	ClassGraph	-- Reading jarfile metadata
2018-08-30T14:21:54.129+0200	ClassGraph	---- Zipfile suffix is not a valid package root: !/classes
2018-08-30T14:21:54.129+0200	ClassGraph	---- Child path component classes in jarfile /home/als/Downloads/ProjectWithAnnotations.iar is a directory, not a file -- using as scanning root
2018-08-30T14:21:54.131+0200	ClassGraph	---- Scanning jarfile/home/als/Downloads/ProjectWithAnnotations.iar (took 0.003155 sec)
2018-08-30T14:21:54.139+0200	ClassGraph	-- Final classpath element order:
2018-08-30T14:21:54.139+0200	ClassGraph	---- 0: /home/als/Downloads/ProjectWithAnnotations.iar!/classes -> /home/als/Downloads/ProjectWithAnnotations.iar
2018-08-30T14:21:54.139+0200	ClassGraph	-- Scanning filenames within classpath elements
2018-08-30T14:21:54.140+0200	ClassGraph	---- Scanning jarfile classpath entry /home/als/Downloads/ProjectWithAnnotations.iar!/classes ; canonical path: /home/als/Downloads/ProjectWithAnnotations.iar (took 0.004412 sec)
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: .classpath
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: .project
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: .settings/.jsdtscope
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: .settings/ch.ivyteam.ivy.designer.prefs
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: .settings/org.eclipse.jdt.core.prefs
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: .settings/org.eclipse.wst.common.component
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: .settings/org.eclipse.wst.common.project.facet.core.prefs.xml
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: .settings/org.eclipse.wst.common.project.facet.core.xml
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: .settings/org.eclipse.wst.css.core.prefs
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: .settings/org.eclipse.wst.jsdt.ui.superType.container
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: .settings/org.eclipse.wst.jsdt.ui.superType.name
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: .ulcproperties
2018-08-30T14:21:54.144+0200	ClassGraph	------ Found whitelisted file: META-INF/persistence.xml
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: classes/META-INF/persistence.xml
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: classes/ch/ivyteam/test/MyManagedBean.class
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: classes/project/with/annotations/Data.class
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: cms/Layouts/1Axonivy/1485F67ACAC259D7.jsp
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: cms/Layouts/1Axonivy/co.meta
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: cms/Layouts/1PanelWithHeaderFooter/1179B65C31F3A109.jsp
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: cms/Layouts/1PanelWithHeaderFooter/co.meta
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: cms/Layouts/1centeredPanel/10EC2DD258C49EAF.jsp
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: cms/Layouts/1centeredPanel/co.meta
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: cms/Layouts/co.meta
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: cms/Project/Banner/1178345D699AF3CE.png
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: cms/Project/Banner/co.meta
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: cms/Project/FooterText/1178C05004C41EBD.data
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: cms/Project/FooterText/co.meta
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: cms/Project/HeaderText/1178C05685DDA3D7.data
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: cms/Project/HeaderText/co.meta
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: cms/Project/co.meta
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: cms/Styles/Axonivy/148600F8CD2D3747.css
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: cms/Styles/Axonivy/co.meta
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: cms/Styles/Blue/10EC2705822F2C1A.css
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: cms/Styles/Blue/co.meta
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: cms/Styles/Classic/10EC278AA7BE62DA.css
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: cms/Styles/Classic/co.meta
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: cms/Styles/Cool/10EC278D4F2834D5.css
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: cms/Styles/Cool/co.meta
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: cms/Styles/Ivy/10EC2791ECD64576.css
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: cms/Styles/Ivy/co.meta
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: cms/Styles/co.meta
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: cms/cms.meta
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: cms/co.meta
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: cms/system/co.meta
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: cms/system/validation/co.meta
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: cms/system/validation/mandatoryerrormessage/12655B706C5E443E.data
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: cms/system/validation/mandatoryerrormessage/co.meta
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: config/BooleanFormat/co.meta
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RButton/co.meta
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RCheckBox/co.meta
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RCheckBoxMenuItem/co.meta
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RComboBox/co.meta
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RComboBoxCellWidget/co.meta
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RDatePicker/co.meta
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RFiller/co.meta
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RHtmlPane/co.meta
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RHyperlink/co.meta
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RLabel/co.meta
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RList/co.meta
2018-08-30T14:21:54.142+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RLookupTextField/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RMenuItem/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RPasswordField/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RProgressBar/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RRadioButton/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RRadioButtonMenuItem/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RScrollBar/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RSlider/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RTable/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RTableCell/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RTableTree/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RTextArea/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RTextField/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RTextFieldCellWidget/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RToggleButton/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/RTree/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ComponentStyle/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ContainerStyle/RBorderLayoutPane/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ContainerStyle/RBoxLayoutPane/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ContainerStyle/RBoxPane/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ContainerStyle/RCardPane/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ContainerStyle/RCollapsiblePane/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ContainerStyle/RFlowLayoutPane/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ContainerStyle/RGridBagLayoutPane/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ContainerStyle/RGridLayoutPane/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ContainerStyle/RScrollPane/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ContainerStyle/RSplitPane/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ContainerStyle/RTabbedPane/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ContainerStyle/RTaskPane/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ContainerStyle/RTaskPaneContainer/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ContainerStyle/RToolBar/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/ContainerStyle/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/DateFormat/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/DateTimeFormat/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/DateTimeWidgetValidation/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/DateWidgetValidation/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/Environments/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/GlobalVariables/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/NumberFormat/co.meta
2018-08-30T14:21:54.143+0200	ClassGraph	------ Found whitelisted file: config/NumberWidgetValidation/co.meta
2018-08-30T14:21:54.144+0200	ClassGraph	------ Found whitelisted file: config/PercentWidgetValidation/co.meta
2018-08-30T14:21:54.144+0200	ClassGraph	------ Found whitelisted file: config/RegexWidgetValidation/co.meta
2018-08-30T14:21:54.144+0200	ClassGraph	------ Found whitelisted file: config/RichDialogWindowTypes/co.meta
2018-08-30T14:21:54.144+0200	ClassGraph	------ Found whitelisted file: config/SmartTable/co.meta
2018-08-30T14:21:54.144+0200	ClassGraph	------ Found whitelisted file: config/StringFormat/co.meta
2018-08-30T14:21:54.144+0200	ClassGraph	------ Found whitelisted file: config/TimeFormat/co.meta
2018-08-30T14:21:54.144+0200	ClassGraph	------ Found whitelisted file: config/TimeWidgetValidation/co.meta
2018-08-30T14:21:54.144+0200	ClassGraph	------ Found whitelisted file: config/cms.meta
2018-08-30T14:21:54.144+0200	ClassGraph	------ Found whitelisted file: config/co.meta
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: databases.dbConfig
2018-08-30T14:21:54.144+0200	ClassGraph	------ Found whitelisted file: dataclasses/project/with/annotations/Data.ivyClass
2018-08-30T14:21:54.141+0200	ClassGraph	------ Found whitelisted file: overrides.overrideconfig
2018-08-30T14:21:54.140+0200	ClassGraph	------ Found whitelisted file: pom.xml
2018-08-30T14:21:54.140+0200	ClassGraph	------ Found whitelisted file: restClients.restConfig
2018-08-30T14:21:54.140+0200	ClassGraph	------ Found whitelisted file: roles.roleconfig
2018-08-30T14:21:54.144+0200	ClassGraph	------ Found whitelisted file: src/META-INF/persistence.xml
2018-08-30T14:21:54.144+0200	ClassGraph	------ Found whitelisted file: src/ch/ivyteam/test/MyManagedBean.java
2018-08-30T14:21:54.144+0200	ClassGraph	------ Found whitelisted file: src_dataClasses/project/with/annotations/Data.java
2018-08-30T14:21:54.140+0200	ClassGraph	------ Found whitelisted file: testusers.userconfig
2018-08-30T14:21:54.144+0200	ClassGraph	------ Found whitelisted file: webContent/META-INF/MANIFEST.MF
2018-08-30T14:21:54.144+0200	ClassGraph	------ Found whitelisted file: webContent/WEB-INF/faces-config.xml
2018-08-30T14:21:54.140+0200	ClassGraph	------ Found whitelisted file: webservice.wsconfig
2018-08-30T14:21:54.145+0200	ClassGraph	Masking classpath files
2018-08-30T14:21:54.145+0200	ClassGraph	Scanning classfile binary headers (took 0.006012 sec)
2018-08-30T14:21:54.146+0200	ClassGraph	-- Parsing classfile [jar /home/als/Downloads/ProjectWithAnnotations.iar]/classes/ch/ivyteam/test/MyManagedBean.class (took 0.002020 sec)
2018-08-30T14:21:54.148+0200	ClassGraph	---- Class ch.ivyteam.test.MyManagedBean is at incorrect relative path classes/ch/ivyteam/test/MyManagedBean.class -- ignoring
2018-08-30T14:21:54.148+0200	ClassGraph	-- Parsing classfile [jar /home/als/Downloads/ProjectWithAnnotations.iar]/classes/project/with/annotations/Data.class (took 0.000064 sec)
2018-08-30T14:21:54.148+0200	ClassGraph	---- Class project.with.annotations.Data is at incorrect relative path classes/project/with/annotations/Data.class -- ignoring
2018-08-30T14:21:54.151+0200	ClassGraph	Building class graph (took 0.000063 sec)
2018-08-30T14:21:54.154+0200	ClassGraph	Completed (took 0.034658 sec)

```

**Comment by alexsuter** [comment]
I think I found my mistake:
`.overrideClasspath("/tmp/custom.jar!/classes")`
should be
`.overrideClasspath("/tmp/custom.jar!classes")`

**Comment by lukehutch** [comment]
Actually there was a bigger problem here, you uncovered a bug with ClassGraph: firstly, it should be robust to having a leading `/` in front of a package root. But secondly in some zipfiles, there is no zip entry created for directories, only for files, and ClassGraph was depending upon the existence of a directory classpath entry to allow package roots to be added.

I fixed these issues and also made a bunch of other cleanup and robustness fixes. This will be in the next version (4.1.4).

Thanks for the report!

**Comment by alexsuter** [comment]
Thank you.

I think there are some cases or some zips, where it still not work properly. Maybe you can reproduce that with my 'iar' file. It's just a zip/jar file with the suffix 'iar'.

https://wetransfer.com/downloads/cef9559bcf1b180806ce383cc785fdbf20180831061124/17e64dc300687d77aacf10b02149d41f20180831061124/800a69

```
2018-08-31T08:07:01.580+0200	ClassGraph	ClassGraph version 4.1.4
2018-08-31T08:07:01.585+0200	ClassGraph	Operating system: Linux 4.15.0-33-generic amd64
2018-08-31T08:07:01.585+0200	ClassGraph	Java version: 1.8.0_181 / 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13 (Oracle Corporation)
2018-08-31T08:07:01.585+0200	ClassGraph	JRE jars:
2018-08-31T08:07:01.585+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar
2018-08-31T08:07:01.585+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar
2018-08-31T08:07:01.585+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/cldrdata.jar
2018-08-31T08:07:01.585+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/dnsns.jar
2018-08-31T08:07:01.585+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/icedtea-sound.jar
2018-08-31T08:07:01.585+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/jaccess.jar
2018-08-31T08:07:01.585+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/java-atk-wrapper.jar
2018-08-31T08:07:01.585+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/jfxrt.jar
2018-08-31T08:07:01.585+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/localedata.jar
2018-08-31T08:07:01.585+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/nashorn.jar
2018-08-31T08:07:01.585+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunec.jar
2018-08-31T08:07:01.585+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunjce_provider.jar
2018-08-31T08:07:01.585+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunpkcs11.jar
2018-08-31T08:07:01.585+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/zipfs.jar
2018-08-31T08:07:01.585+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar
2018-08-31T08:07:01.585+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfxswt.jar
2018-08-31T08:07:01.585+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar
2018-08-31T08:07:01.585+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/management-agent.jar
2018-08-31T08:07:01.585+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar
2018-08-31T08:07:01.585+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/lib/ant-javafx.jar
2018-08-31T08:07:01.585+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/lib/dt.jar
2018-08-31T08:07:01.585+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/lib/javafx-mx.jar
2018-08-31T08:07:01.585+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/lib/jconsole.jar
2018-08-31T08:07:01.585+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/lib/sa-jdi.jar
2018-08-31T08:07:01.585+0200	ClassGraph	-- /usr/lib/jvm/java-8-openjdk-amd64/lib/tools.jar
2018-08-31T08:07:01.589+0200	ClassGraph	ScanSpec:
2018-08-31T08:07:01.589+0200	ClassGraph	-- packageWhiteBlackList: 
2018-08-31T08:07:01.589+0200	ClassGraph	-- packagePrefixWhiteBlackList: 
2018-08-31T08:07:01.589+0200	ClassGraph	-- pathWhiteBlackList: 
2018-08-31T08:07:01.589+0200	ClassGraph	-- pathPrefixWhiteBlackList: 
2018-08-31T08:07:01.589+0200	ClassGraph	-- classWhiteBlackList: 
2018-08-31T08:07:01.590+0200	ClassGraph	-- classfilePathWhiteBlackList: 
2018-08-31T08:07:01.590+0200	ClassGraph	-- classPackageWhiteBlackList: 
2018-08-31T08:07:01.590+0200	ClassGraph	-- classPackagePathWhiteBlackList: 
2018-08-31T08:07:01.590+0200	ClassGraph	-- moduleWhiteBlackList: 
2018-08-31T08:07:01.590+0200	ClassGraph	-- jarWhiteBlackList: 
2018-08-31T08:07:01.590+0200	ClassGraph	-- libOrExtJarWhiteBlackList: 
2018-08-31T08:07:01.590+0200	ClassGraph	-- performScan: true
2018-08-31T08:07:01.590+0200	ClassGraph	-- scanJars: true
2018-08-31T08:07:01.590+0200	ClassGraph	-- scanNestedJars: true
2018-08-31T08:07:01.590+0200	ClassGraph	-- scanDirs: true
2018-08-31T08:07:01.590+0200	ClassGraph	-- scanModules: true
2018-08-31T08:07:01.590+0200	ClassGraph	-- enableClassInfo: true
2018-08-31T08:07:01.590+0200	ClassGraph	-- enableFieldInfo: true
2018-08-31T08:07:01.590+0200	ClassGraph	-- enableMethodInfo: true
2018-08-31T08:07:01.590+0200	ClassGraph	-- enableAnnotationInfo: true
2018-08-31T08:07:01.590+0200	ClassGraph	-- enableStaticFinalFieldConstantInitializerValues: true
2018-08-31T08:07:01.590+0200	ClassGraph	-- enableExternalClasses: false
2018-08-31T08:07:01.590+0200	ClassGraph	-- blacklistSystemJarsOrModules: true
2018-08-31T08:07:01.590+0200	ClassGraph	-- ignoreClassVisibility: true
2018-08-31T08:07:01.590+0200	ClassGraph	-- ignoreFieldVisibility: true
2018-08-31T08:07:01.590+0200	ClassGraph	-- ignoreMethodVisibility: true
2018-08-31T08:07:01.590+0200	ClassGraph	-- disableRuntimeInvisibleAnnotations: false
2018-08-31T08:07:01.590+0200	ClassGraph	-- addedClassLoaders: null
2018-08-31T08:07:01.590+0200	ClassGraph	-- overrideClassLoaders: null
2018-08-31T08:07:01.590+0200	ClassGraph	-- overrideClasspath: /tmp/myProject4346149984158988763.iar!/classes
2018-08-31T08:07:01.590+0200	ClassGraph	-- classpathElementFilters: null
2018-08-31T08:07:01.591+0200	ClassGraph	-- extraClassLoaderHandlers: []
2018-08-31T08:07:01.591+0200	ClassGraph	-- initializeLoadedClasses: false
2018-08-31T08:07:01.591+0200	ClassGraph	-- removeTemporaryFilesAfterScan: false
2018-08-31T08:07:01.591+0200	ClassGraph	-- ignoreParentClassLoaders: false
2018-08-31T08:07:01.591+0200	ClassGraph	-- stripSFXHeader: false
2018-08-31T08:07:01.591+0200	ClassGraph	Finding classpath entries
2018-08-31T08:07:01.601+0200	ClassGraph	-- Getting raw classpath elements
2018-08-31T08:07:01.602+0200	ClassGraph	---- Finding ClassLoaders and modules
2018-08-31T08:07:01.605+0200	ClassGraph	------ Found ClassLoaders:
2018-08-31T08:07:01.606+0200	ClassGraph	-------- sun.misc.Launcher$AppClassLoader@18b4aac2
2018-08-31T08:07:01.606+0200	ClassGraph	-------- java.net.URLClassLoader@1b6d5a61
2018-08-31T08:07:01.606+0200	ClassGraph	------ Adding fallback URLClassLoader for overriden classpath: java.net.URLClassLoader@1b6d5a61
2018-08-31T08:07:01.606+0200	ClassGraph	------ Found system modules:
2018-08-31T08:07:01.606+0200	ClassGraph	-------- [None]
2018-08-31T08:07:01.606+0200	ClassGraph	------ Found non-system modules:
2018-08-31T08:07:01.606+0200	ClassGraph	-------- [None]
2018-08-31T08:07:01.607+0200	ClassGraph	------ Overriding classpath with: /tmp/myProject4346149984158988763.iar!/classes
2018-08-31T08:07:01.607+0200	ClassGraph	-------- Found classpath element: /tmp/myProject4346149984158988763.iar!/classes
2018-08-31T08:07:01.626+0200	ClassGraph	-------- WARNING: when the classpath is overridden, there is no guarantee that the classes found by classpath scanning will be the same as the classes loaded by the context classloader
2018-08-31T08:07:01.626+0200	ClassGraph	-- Reading jarfile metadata
2018-08-31T08:07:01.632+0200	ClassGraph	---- Reading /tmp/myProject4346149984158988763.iar!/classes
2018-08-31T08:07:24.512+0200	ClassGraph	------ Ignoring invalid classpath element: /tmp/myProject4346149984158988763.iar!/classes : java.io.IOException: Exception while locating jarfile /tmp/myProject4346149984158988763.iar!/classes : java.lang.NullPointerException
2018-08-31T08:07:24.516+0200	ClassGraph	-- Final classpath element order:
2018-08-31T08:07:24.518+0200	ClassGraph	-- Scanning filenames within classpath elements
2018-08-31T08:07:24.521+0200	ClassGraph	Masking classpath files
2018-08-31T08:07:24.521+0200	ClassGraph	Scanning classfile binary headers (took 0.002657 sec)
2018-08-31T08:07:24.524+0200	ClassGraph	Building class graph (took 0.000244 sec
```)
2018-08-31T08:07:24.528+0200	ClassGraph	Completed (took 22.927448 sec)

**Comment by lukehutch** [comment]
Actually `NullPointerException` should never happen. So this is a bug for sure, probably introduced by the newest code changes. Unfortunately I don't add a stacktrace to the code in the case of an `IOException`, which is thrown as a result of the `NullPointerException`. Can you please go to the catch block in ClasspathOrModulePathEntry.java, line 285, and insert `e.printStackTrace();`, then build the library (`mvn package`), and let me know where this NPE is thrown?

**Comment by alexsuter** [comment]
> java.lang.NullPointerException
> 	at io.github.classgraph.utils.NestedJarHandler$4.newInstance(NestedJarHandler.java:261)
> 	at io.github.classgraph.utils.NestedJarHandler$4.newInstance(NestedJarHandler.java:134)
> 	at io.github.classgraph.utils.SingletonMap.createSingleton(SingletonMap.java:96)
> 	at io.github.classgraph.utils.SingletonMap.getOrCreateSingleton(SingletonMap.java:135)
> 	at io.github.classgraph.utils.NestedJarHandler.getInnermostNestedJar(NestedJarHandler.java:449)
> 	at io.github.classgraph.utils.ClasspathOrModulePathEntry.getFile(ClasspathOrModulePathEntry.java:267)
> 	at io.github.classgraph.utils.ClasspathOrModulePathEntry.exists(ClasspathOrModulePathEntry.java:385)
> 	at io.github.classgraph.utils.ClasspathOrModulePathEntry.isValidClasspathElement(ClasspathOrModulePathEntry.java:415)
> 	at io.github.classgraph.Scanner$ClasspathOrModulePathEntryToClasspathElementMap.newInstance(Scanner.java:125)
> 	at io.github.classgraph.Scanner$ClasspathOrModulePathEntryToClasspathElementMap.newInstance(Scanner.java:99)
> 	at io.github.classgraph.utils.SingletonMap.createSingleton(SingletonMap.java:96)
> 	at io.github.classgraph.utils.SingletonMap.getOrCreateSingleton(SingletonMap.java:135)
> 	at io.github.classgraph.Scanner$1.processWorkUnit(Scanner.java:385)
> 	at io.github.classgraph.Scanner$1.processWorkUnit(Scanner.java:373)
> 	at io.github.classgraph.utils.WorkQueue.runWorkLoop(WorkQueue.java:245)
> 	at io.github.classgraph.utils.WorkQueue.access$000(WorkQueue.java:46)
> 	at io.github.classgraph.utils.WorkQueue$1.call(WorkQueue.java:205)
> 	at io.github.classgraph.utils.WorkQueue$1.call(WorkQueue.java:202)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
>

**Comment by alexsuter** [comment]
I recommend that you wrap occured exceptions:
Refactoring code like this:
`throw new IOException("Exception while locating jarfile " + relativePath + " : " + e);`
to:
`throw new IOException("Exception while locating jarfile " + relativePath + " : ", e);`
So the cause will be part of the new exception.
At the end you can make somewehere a catch everything and log the cause.

**Comment by lukehutch** [comment]
Actually almost all the exceptions that were being thrown in ClassGraph used to be of the form you suggested, but that created a lot of backtrace info in the logs in cases where for example the classpath contained references to non-existent jars or directories, so once the code was debugged and working (until this latest regression was introduced), I got rid of backtraces in cases of `IOException`, since in every case, if an `IOException` was logged, it was something wrong with the classpath, rather than with ClassGraph. I went overboard here though and caught all exceptions, not just `IOException`. The version I checked in that you tested (in f0387ff346b2d45ce3ebc4a92466d5c9844aea41) accomplishes more or less what you were suggesting, except that non-`IOException`s are now separately logged on the spot, which will help catch these sorts of issues in the future.

**Comment by lukehutch** [comment]
The fix is released in 4.1.5 -- please test that and let me know if it works for you. Thanks!

**Comment by alexsuter** [comment]
Thanks. Can you make it available on maven central?

**Comment by alexsuter** [comment]
I have built the current master on my own, and it seems to work now for my jar file.

**Comment by lukehutch** [comment]
OK, thanks for testing. Please open another bug if there are more problems.

**Comment by lukehutch** [comment]
Re. Maven Central -- that happens automatically, but sometimes it takes a few hours, and I can't speed that up unfortunately.
